### ISSUE TITLE
Session Object Doesn't Honor Proxy

### ISSUE THREAD

**Issue by achapkowski** [psf/requests#6059] opened 2022-02-05 01:15 UTC
In 2.27.1, if I define a proxy as this:

```proxy = {"http": "http://127.0.0.1:8888", "https": "http://127.0.0.1:8888"}```

and then I create a session

```python
import requests
s = requests.Session()
s.proxies = proxy
s.get("https://google.com").text
```

The proxy setting is not honored.

A solution can be inserted here:

```
proxies = proxies or self.proxies or {}
```

This can be found in the PR:

**Comment by nateprewitt** [comment] 2022-02-16 20:02
Dupe of #2018.

**Closed by nateprewitt** 2022-02-16 20:02 UTC

**Comment by dmich2** [comment] 2022-02-17 16:42
To quote @nateprewitt from way back in Aug 11, 2016:

> It may be worth noting that it's PR #2839 that fixes this.
> 
> _Originally posted by @nateprewitt in https://github.com/psf/requests/issues/3506#issuecomment-239304816_
> 

[BTW that pr does exactly what I was attempting to suggest in my original comment to @achapkowski 's pr :) ]

I guess one reason why this isn't as urgent as one might think, is there is a simple if annoying workaround. If you need to ensure proxy use, ALWAY specify it in your requests instead of relying on the session.proxies.

I suppose one thing that could be done immediately is change the documentation to warn people NOT to depend on session.proxies if there is a chance that they also have environmental proxies set? I was using the free Psiphon proxy on Windows so it was blazingly obvious something was going wrong because I kept getting 

    ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)

exceptions whenever Psiphon was connected. Helpfully, the error message also suggests that you change your https proxy url to use the http url instead, which turns out to work as long as you can get it set correctly, which is when I ran into this bug.

**Comment by nateprewitt** [comment] 2022-02-17 16:49
@dmich2 I'd accept a succinct sentence or two [here](https://github.com/psf/requests/blame/main/docs/user/advanced.rst#L605) to clarify this behavior if people think it would be helpful. I agree that's probably the best immediate term solution.

**Comment by dmich2** [comment] 2022-02-17 18:07
@nateprewitt How about:

```
WARNING: If environmental proxies (those returned by 
`urllib.request.getproxies()<https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies>`) exist,
then with Requests versions prior to 3.0 those environmental proxies will OVERRIDE session.proxies. 
To ensure the use of proxies in the presence of environmental proxies, explicitly specify the ``proxies`` argument
on any request methods as above.
```

although I think it should go [here](https://github.com/psf/requests/blame/main/docs/user/advanced.rst#L620), after the discussion of environment variables.

**Comment by dmich2** [comment] 2022-02-17 18:31
@nateprewitt How about:

```
.. warning::  In Requests versions prior to 3.0, overriding these environmental proxies (those returned by 
   `urllib.request.getproxies()<https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies>`),
   by using ``session.proxies.update(proxies)`` does not work correctly. 
   To ensure the use of proxies in the presence of environmental proxies, explicitly specify the ``proxies`` argument
   on all individual requests as initially explained above.

   See `PR #2839 <https://github.com/psf/requests/pull/2839>` for details.
```

although I think it should go [here](https://github.com/psf/requests/blame/main/docs/user/advanced.rst#L620) after the discussion of environment variables.

**Comment by achapkowski** [comment] 2022-02-17 18:41
@dmich2 this would be very helpful.  Thank you

**Comment by dmich2** [comment] 2022-02-17 19:05
Reading them again it would be better to reference Issue #2018 (which has more background) rather than PR #2839 (which is what actually fixed the bug) in the documentation. 

There's been a whole slew of discussions on this over the years so it's hard to choose :)

**Comment by nateprewitt** [comment] 2022-02-17 19:57
> although I think it should go [here](https://github.com/psf/requests/blame/main/docs/user/advanced.rst#L620) after the discussion of environment variables.

We're trying to add the warning from a usage perspective. The `Session.proxies` user is likely not going to care about or read the environment sub-section. We probably want to keep it as close to the impacted section as possible.


I think the wording looks good. I've made a few inline edits to omit an explicit version call out and rephrase this from `session.proxies` perspective rather than environment. Let me know what you think.
```
.. warning::  Setting ``session.proxies`` may behave differently than expected. Values provided will be overwritten by
      environmental proxies (those returned by `urllib.request.getproxies(<https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies>`),
      To ensure the use of proxies in the presence of environmental proxies, explicitly specify the ``proxies`` argument
      on all individual requests as initially explained above.

   See `PR #2018 <https://github.com/psf/requests/pull/2018>` for details.
```

**Comment by dmich2** [comment] 2022-02-17 21:00
Looks good. When 3.0 comes out, someone will have to remember to retest and probably reword/remove the warning.
