### ISSUE TITLE
sphinx.ext.autodoc intersphinx_mapping for python-requests throws SSLError

### ISSUE THREAD

**Issue by serbant** [psf/requests#5218] opened 2019-10-01 19:44 UTC
Summary.

Sphinx documentation 'make html' throws warning about https://2.python-requests.org/en/master/objects.inv

## Expected Result

Sphinx make can pull the objects.inv without problems

## Actual Result

```
(phsa_venv) phsa@lvmsocq01:~/p_soc_auto/docs$ make html
Running Sphinx v2.1.2
loading pickled environment... done
loading intersphinx inventory from https://2.python-requests.org/en/master/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://2.python-requests.org/en/master/objects.inv' not fetchable due to <class 'requests.exceptions.SSLError'>: HTTPSConnectionPool(host='2.python-requests.org', port=443): Max retries exceeded with url: /en/master/objects.inv (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:833)'),))
...
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in build/html.
(phsa_venv) phsa@lvmsocq01:~/p_soc_auto/docs$ 
```

## Reproduction Steps

This is the relevant extract from the Sphinx conf.py file:

```python
extensions = [
    'sphinx.ext.autodoc',
    'IPython.sphinxext.ipython_directive',
    'IPython.sphinxext.ipython_console_highlighting',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'sphinx.ext.inheritance_diagram',
    'celery.contrib.sphinx',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
    'sphinx.ext.autosummary',
    'sphinxcontrib.plantuml',
]

# ...

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'django': ('http://docs.djangoproject.com/en/2.2/',
               'http://docs.djangoproject.com/en/2.2/_objects/'),
    'urllib3': ('http://urllib3.readthedocs.org/en/latest', None),
    'requests': ('https://2.python-requests.org/en/master/', None), }

```

Then run a Sphinx 'make html'

## System Information

    $ python -m requests.help

```
(phsa_venv) phsa@lvmsocq01:~/p_soc_auto$ python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.5"
  },
  "platform": {
    "release": "3.10.0-862.3.2.el7.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": false
}

```

**Comment by volans-** [comment] 2019-10-10 09:53
Isn't this a duplicate of #5212 ?

**Comment by Natim** [comment] 2020-09-18 08:38
Fixed by using https://requests.readthedocs.io/en/master/ for intersphinx configuration.

**Comment by nateprewitt** [comment] 2020-11-10 00:44
I don't see a point in recent history for Requests where we've had an intersphinx_mapping like this. Assuming this is one you've created, Natim's response is correct. We recommend using the requests.readthedocs.io going forward.

**Closed by nateprewitt** 2020-11-10 00:44 UTC

**Comment by Natim** [comment] 2020-11-10 08:14
> I don't see a point in recent history for Requests where we've had an intersphinx_mapping like this.

I think that's a Sphinx capability.
