### ISSUE TITLE
Can't unset the User-Agent

### ISSUE THREAD

**Issue by marwanpro** [psf/requests#6033] opened 2022-01-06 12:51 UTC
Impossible to unset the User-Agent, if I pass `headers = { 'User-Agent': None }`, urllib3 UA will be set as a fallback

I expect to not have any User-Agent sent to the webserver

![image](https://user-images.githubusercontent.com/2185992/148385822-0a88da4f-9165-4f66-94e1-6769c6607f9b.png)

## Reproduction Steps

```python
import requests

headers = {
    'User-Agent': None
}

proxies = {
    'https': 'http://127.0.0.1:8888'
}

response = requests.post(
    'http://localhost:8888/',
    data={'name': 'test'},
    headers=headers,
    proxies=proxies,
    verify=False
)

exit()
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.9"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.1"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.27.1"
  },
  "system_ssl": {
    "version": "101010cf"
  },
  "urllib3": {
    "version": "1.26.7"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment] 2022-01-06 12:52
I thought this was a duplicate of the other issue you commented, sorry for the misclick

**Comment by notAutomne** [comment] 2022-01-06 12:53
> I thought this was a duplicate of the other issue you commented, sorry for the misclick

No problem, I have the same issue even without session

**Comment by sigmavirus24** [comment] 2022-01-06 12:57
Yup. I see that from the other issue too. Thanks for the clear issue

**Comment by notAutomne** [comment] 2022-01-06 14:25
@sigmavirus24 Your PR #5693 solves the issue, why not merging it ?

I merged your PR with the latest commit on my local branch, only one test fails : TestRequests.test_header_remove_is_case_insensitive

**Comment by nateprewitt** [comment] 2022-01-06 14:32
Hi @marwanpro, there are still some usability concerns with that patch. For the time being, you are free to do the same thing and pass urllib3's SKIP_HEADER in your request to disable their defaulted values.

```
headers = {'user-agent': SKIP_HEADER, ... }

req = Request('GET', someurl)
prep = req.prepare()
prep.headers = headers
```

**Comment by nateprewitt** [comment] 2022-01-06 16:21
This does appear to be a duplicate of #5671 too. Is there a subtlety I'm missing @sigmavirus24? If not, I'll port the current workaround to that ticket and resolve this one so we can keep tracking centralized.

**Closed** 2022-01-06 17:27 UTC
