### ISSUE TITLE
SSLError - CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by mimansa-dev** [psf/requests#5951] opened 2021-10-06 17:50 UTC
## Summary

Started getting SSLError when invoking API using requests module.
SSLError: HTTPSConnectionPool(host='<HOST URL>, port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))

Just to add that this is on RHEL

>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.1e-fips 11 Feb 2013'

The system openssl is 
Version     : 1.0.1e, 
Release     : 58.el6_10

python was built using source.

## Expected Result

Was not expecting an SSLError. This is not a problem with the source website as the same call works fine using postman. Could this have anything to do with letsencryt root certificate expiration?

## Actual Result
SSLError: HTTPSConnectionPool(host='<HOST URL>, port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))

## Reproduction Steps

```
Invoke API using python requests and without verify=False

```

## System Information

Just to add that this is on RHEL

>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.1e-fips 11 Feb 2013'

The system openssl is 
Version     : 1.0.1e, 
Release     : 58.el6_10

python was built using source.

    $ python -m requests.help

```
{
  "chardet": {
    "version": "4.0.0"
  },
  "charset_normalizer": {
    "version": null
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.9"
  },
  "platform": {
    "release": "2.6.32-754.9.1.el6.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.26.0"
  },
  "system_ssl": {
    "version": "1000105f"
  },
  "urllib3": {
    "version": "1.26.6"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sethmlarson** [comment] 2021-10-06 20:05
Might be getting hit by LetsEncrypt's old root CA expiring. Try upgrading certifi or whatever certificates you're using on the OS.

**Comment by sigmavirus24** [comment] 2021-10-06 20:33
Duplicate of https://github.com/certifi/python-certifi/issues/164

**Closed by sigmavirus24** 2021-10-06 20:33 UTC
