### ISSUE TITLE
requests.request does not check method parameter

### ISSUE THREAD

**Issue by Michal-Martinek** [psf/requests#6692] opened 2024-04-30 16:15 UTC
```
res = requests.request(method='155661', url='https...')
```
doesn't raise any error (warning) for totally unreasonable value for **method** parameter.

It leads to bugs.

**Comment by nateprewitt** [comment] 2024-04-30 17:44
Hi @Michal-Martinek, this is intentional design. There are many verbs we do not support directly, but may be used such as WebDAV. We don't intend to enumerate all possible options in our library, so it is left to the end user to determine their needs.

You'll find you can successfully send your request to well-functioning web servers, so I don't think we intend to change the existing behavior. We should be clear about what "bug" means in this case. If there is unexpected behavior in Requests, can you please provide an exact stacktrace or behavior issue? If the problem is the web server returns a non-200 response, I'd propose we close this as working as intended.

**Closed** 2024-05-01 01:43 UTC
Labels: Propose Close
