### ISSUE TITLE
Redirect resolved even though allow_redirects is set to False causing exception for unsupported connection adapter

### ISSUE THREAD

**Issue by fevertree** [psf/requests#4362] opened 2017-10-31 13:11 UTC
I'm currently mocking an API that is consumed by an Android application.
One of the API responses contains a redirect to a custom URL schema `app://` in the `Location` header

Since I am not interested in my mocked API client in following the redirect (which would raise an InvalidSchema exception anyway), I have set `allow_redirects = False` on my session object. Although the redirect is not fired, it is still being resolved, causing an exception due to the missing url adapter.

## Expected Result
Since I'm not interested in the redirects being followed, it would make sense to not resolve the redirected request in the first place.

## How to reproduce

```python
import requests

S = requests.session()
S.allow_redirects = False
destination = https://somesite.example # URL with a redirect to a non-standard protocol
S.get(url=destination)
```
Response headers (example):
```
HTTP/1.1 302 Found
Server: Apache-Coyote
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Location: app://api-test.somesite.example?q=example
Content-Language: en
Content-Length: 0
Date: Tue, 31 Oct 2017 12:39:17 GMT
Connection: close
```

Exception thrown by code:
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    S.get(url=destination)
in get
    return self.request('GET', url, **kwargs)
  File ~/.local/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 661, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 214, in resolve_redirects
    **adapter_kwargs
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 633, in send
    adapter = self.get_adapter(url=request.url)
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 717, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'app://api-test.somesite.com?q=example'

```

## Actual Result
InvalidSchema exception

**Comment by Lukasa** [comment] 2017-10-31 17:47
@kennethreitz This is the result of `Response.next`, which you added. Mind taking a look?

**Comment by Sriharivignesh** [comment] 2017-11-19 03:23
@fevertree can you try this and see if you still get the exception?

```
import requests

S = requests.session()
destination = https://somesite.example # URL with a redirect to a non-standard protocol
S.get(url=destination, allow_redirects=False)
```

As far as I know `S.allow_redirects = False` doesn't do anything.

**Comment by kennethreitz** [comment] 2018-03-10 20:58
Hmm, never got this notification.

**Comment by martin-kokos** [comment] 2018-06-11 20:19
I cannot reproduce this as of 2.18.4
fails on `allow_redirects=True`
works as expected with `allow_redirects=False`

test server:
```
from aiohttp import web

async def app_redir(request):
    return web.HTTPSeeOther('app://test')

app = web.Application()
app.add_routes([web.get('/', app_redir)])
web.run_app(app)
```

**Comment by luckydenis** [comment] 2021-02-08 15:37
Good evening. 
I was able to reproduce the error.

https://github.com/psf/requests/blob/8c211a96cdbe9fe320d63d9e1ae15c5c07e179f8/requests/sessions.py#L730-L742


server.py
```python
from aiohttp import web

async def app_redir(request):
    return web.HTTPSeeOther('app://test')

app = web.Application()
app.add_routes([web.get('/', app_redir)])
web.run_app(app)
```

tester.py
```python
import requests

s = requests.session()
s.allow_redirects = False
destination = "0.0.0.0:8080"
s.get(url=destination)
```
We get an error message because we don't pass the check by this list. 

https://github.com/psf/requests/blob/8c211a96cdbe9fe320d63d9e1ae15c5c07e179f8/requests/sessions.py#L419-L423

But it seems to me that the error should be: `requests.exceptions.MissingSchema`. The error slips in here.
https://github.com/psf/requests/blob/8c211a96cdbe9fe320d63d9e1ae15c5c07e179f8/requests/models.py#L373-L378

**Comment by nateprewitt** [comment] 2021-12-29 02:32
Reading back through this issue I think we ended up going down the wrong rabbit hole. The original reported issue isn't a bug. The error is reproducible at least as far back as 2.13.0, prior to the inclusion of `next`. Session has never supported direct assignment of `allow_redirects`, at least not in Requests 2.x. As noted in the comments above, it's only usable in the  Session `request` API as a kwarg.

The issue raised by @LuckyDenis is tangential to the original problem and can be addressed in PR. I'll resolve this since there doesn't appear to be anything left to do.

**Closed by nateprewitt** 2021-12-29 02:32 UTC
Labels: Bug
