### ISSUE TITLE
requests raise broken pipe, but postman return 500 status

### ISSUE THREAD

**Issue by EmptyRabbit** [psf/requests#5296] opened 2019-12-23 08:13 UTC
when upload big file(bigger than server limit). I expect return response with 500 status

1、I tried postman to post api, it return 500 error,that what I need

2、I tried requests to post api

here is requests code:
```
with open('invalid_big_license', 'rb') as f:
    test = s.post(
        url,
        headers=headers,
        data=None,
        files={'file': ('invalid_big_license', f)},
        timeout=1200
    )
``` 
requests raise 

`requests.exceptions.ConnectionError: ('Connection aborted.', OSError(41, 'Protocol wrong type for socket'))`
what I need is response return with 500 status

if upload file is under server limit(like 1m),requests is success

**Comment by nateprewitt** [comment] 2020-01-09 17:03
Hi @EmptyRabbit, this is bad data being returned by the server. The first thing I'd check is if this is specific to the Requests User-Agent. You may need to use something like Wireshark to see what exactly is coming across the wire. From the information provided so far, it doesn't look like this is a defect in Requests though.

I'm going to close this for now since we don't have a reproducible example. Feel free to reopen if you have more information or have found this is reproducible outside of this specific server.

**Closed by nateprewitt** 2020-01-09 17:03 UTC
