### ISSUE TITLE
Using `format` as a query parameter for certain URLs causes `requests` to miss the `?` query string separator

### ISSUE THREAD

**Issue by multimeric** [psf/requests#6198] opened 2022-07-14 02:44 UTC
Using `format` as a query parameter for certain URLs causes `requests` to miss the `?` query string separator

## Expected Result

I expect the `?` separator to be present whenever any query parameters are provided.

## Actual Result

The `?` separator is not present.

## Reproduction Steps''

```python
>>> import requests
>>> requests.__version__
'2.28.1'
>>> requests.get("https://www.uniprot.org/uniprotkb/search", params={"format": "json"}).url
'https://rest.uniprot.org/uniprotkb/searchformat=json'
>>> requests.get("https://www.uniprot.org", params={"format": "json"}).url
'https://rest.uniprot.org/format=json'
>>> requests.get("https://www.uniprot.org/uniprotkb/search", params={"size": "500"}).url
'https://www.uniprot.org/uniprotkb/search?size=500'
>>> requests.get("https://www.google.com", params={"format": "json"}).url
'https://www.google.com/?format=json'
```

Note how the same issue happens in different subdomains of `uniprot.org` but that it doesn't happen with `google.com`

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.7"
  },
  "platform": {
    "release": "5.13.0-52-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "101010cf"
  },
  "urllib3": {
    "version": "1.26.10"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sethmlarson** [comment] 2022-07-14 03:01
The service is returning the incorrect URL to be redirected to in the `Location` header:

```python
import requests

resp = requests.get(
  "https://www.uniprot.org/uniprotkb/search",
  params={"format": "json"},
  allow_redirects=False
)

# The response was sent to the right URL
print(resp.url) # 'https://www.uniprot.org/uniprotkb/search?format=json'

# The response is indeed a redirect
print(resp.status_code) # 301

# Service redirects to the incorrect URL you're seeing
print(resp.headers["Location"]) # 'https://rest.uniprot.org/uniprotkb/searchformat=json'
```

Going to close this as not a bug in Requests.

**Closed by sethmlarson** 2022-07-14 03:01 UTC
