### ISSUE TITLE
parsing of proxy url broken with requests 2.27.0

### ISSUE THREAD

**Issue by anneFly** [psf/requests#6030] opened 2022-01-05 10:22 UTC
It seems like this change https://github.com/psf/requests/pull/5917 unfortunately broke production for us.

We are using a proxy url that follows this scheme: `http://randomstring:randomstring@eu-west-static-04.example.com:9293` (from a service that provides static IPs)

## Expected Result

In 2.26.0 this still works:
```
>>> from requests.utils import prepend_scheme_if_needed
>>> prepend_scheme_if_needed('http://randomstring:randomstring@eu-west-static-04.example.com:9293', 'http')
'http://randomstring:randomstring@eu-west-static-04.example.com:9293'
```

## Actual Result
In 2.27.0 it's broken:
```
>>> from requests.utils import prepend_scheme_if_needed
>>> prepend_scheme_if_needed('http://randomstring:randomstring@eu-west-static-04.example.com:9293', 'http')
'http://eu-west-static-04.example.com:9293'
```

This leads in the end to `ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))` because the url was cut.

## Reproduction Steps

```python
>>> from requests.utils import prepend_scheme_if_needed
>>> prepend_scheme_if_needed('http://randomstring:randomstring@eu-west-static-04.example.com:9293', 'http')
```

## System Information

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.9"
  },
  "cryptography": {
    "version": "36.0.1"
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.9"
  },
  "platform": {
    "release": "5.14.21-2-MANJARO",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "101010df",
    "version": "21.0.0"
  },
  "requests": {
    "version": "2.27.0"
  },
  "system_ssl": {
    "version": "101010df"
  },
  "urllib3": {
    "version": "1.26.7"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": true
}
```

**Comment by nateprewitt** [comment] 2022-01-05 13:22
Hi, @anneFly. Thanks for the report! This is actually a duplicate of #6027 which has been patched in #6028 and will be released sometime today. You can track status in #6029.

**Closed by nateprewitt** 2022-01-05 13:22 UTC
