### ISSUE TITLE
Response history is wrong 

### ISSUE THREAD

**Issue by bucknerns** [psf/requests#6855] opened 2024-12-13 21:57 UTC
History for requests with multiple redirects is incorrect.

## Expected Result

Correct history in history of each request

## Actual Result

second request has itself in the history

## Reproduction Steps

```python

In [2]: import requests
# 301 -> https://www.shorturl.at/LvPoU, 302 -> https://www.google.com, 200 https:/www.google.com
In [3]: r = requests.get("https://shorturl.at/LvPoU")
In [4]: r.history
Out[4]: [<Response [301]>, <Response [302]>]

In [5]: r.history[0].history
Out[5]: []

In [6]: r.history[1].history
Out[6]: [<Response [302]>] # This should be the 301

# Response shouldn't be in it's own history
# Should be False and return [<Response [301]>]
In [7]: r.history[1].history[0] is r.history[1] 
Out[7]: True

```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "5.2.0"
  },
  "charset_normalizer": {
    "version": "3.4.0"
  },
  "cryptography": {
    "version": "43.0.3"
  },
  "idna": {
    "version": "3.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.4"
  },
  "platform": {
    "release": "6.8.0-49-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30300020",
    "version": "24.0.0"
  },
  "requests": {
    "version": "2.32.3"
  },
  "system_ssl": {
    "version": "30000020"
  },
  "urllib3": {
    "version": "2.2.3"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": true
}

```

**Comment by nateprewitt** [comment] 2024-12-13 22:24
This is a duplicate of https://github.com/psf/requests/issues/6295#issuecomment-1427034585.

**Closed by nateprewitt** 2024-12-13 22:24 UTC
