### ISSUE TITLE
Error: AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'

### ISSUE THREAD

**Issue by aiwalter** [psf/requests#6445] opened 2023-05-05 10:23 UTC
Recent `urllib3 2.0.2` seems not compatible with `requests`?
## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```json
{
  "paste": "here"
}
```

**Comment by sigmavirus24** [comment] 2023-05-05 11:56
Duplicate of #6432

You're using an outdated and long deprecated attribute from urllib3 retries in your code somewhere. This isn't a bug in requests

**Closed by sigmavirus24** 2023-05-05 11:56 UTC
