### ISSUE TITLE
How to use Session

### ISSUE THREAD

**Issue by contactparthshah** [psf/requests#5275] opened 2019-11-26 05:05 UTC
```
import requests
import time
from requests.packages import urllib3

#Disable https insecure warnings for verify=False
urllib3.disable_warnings()

with open('1.ts','rb') as fh:
    file_data = fh.read()

def chunk_trans():
    for i in range(0, 3):
        time.sleep(0.1)
        yield file_data

req = requests.Request('POST', 'http://192.168.123.151/1.ts', data=chunk_trans(), headers={'Host':'a.b.c.d'})
prep = req.prepare()
s = requests.Session()
s.send(prep, timeout=2, verify=False, allow_redirects=False)
```

On Server, I am seeing two "Host" headers are being sent. is that expected or I am not doing it correctly?

**Comment by contactparthshah** [comment] 2020-01-06 22:55
can anyone look into this please and help?

**Comment by nateprewitt** [comment] 2020-02-10 05:45
Closing as duplicate of #5274.

**Closed by nateprewitt** 2020-02-10 05:45 UTC
