### ISSUE TITLE
How can I use :authority in requests module

### ISSUE THREAD

**Issue by abirabedinkhan** [psf/requests#6173] opened 2022-06-22 15:44 UTC
Hello,
I am working on project that requires :authority header. When I put that it throws errors!!!
Please HELP ME!!!!!!

**Comment by nateprewitt** [comment] 2022-06-22 16:30
Hi @abirabedinkhan, this is a duplicate of #6167. Please check open and closed issues before opening new ones.

**Closed by nateprewitt** 2022-06-22 16:30 UTC
