### ISSUE TITLE
ssl certificate validation of requests was ignored but the ssl certificate still reported an error

### ISSUE THREAD

**Issue by expzhizhuo** [psf/requests#6729] opened 2024-05-31 06:09 UTC
## Expected Result

Testing on different operating systems, I found it was Caused by SSLError(SSLError(1, '[SSL:) caused by SSLerror (SSLError(1, '[SSL:) SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)')) error, but I did not have a validation problem during one of the validations
![image](https://github.com/psf/requests/assets/64049774/f6fcaa86-8330-4620-b27c-768025f53faa)
Testing on my mac air m2 machine produced the above error, but my demonstration in kali did not have this problem
![image](https://github.com/psf/requests/assets/64049774/b366b4ae-8b5c-4925-bbde-a9777a8de259)
But I tested it with the default python version on ubuntu 22.04 and got the same error message as on my mac
![image](https://github.com/psf/requests/assets/64049774/bf90b75b-0f42-4a8d-a32c-c9e7137f2b2b)

## Actual Result

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='183.237.161.98', port=4433): Max retries exceeded with url: /favicon.ico (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)')))
```

## Reproduction Steps

```python
import requests
response = requests.get(url="https://183.237.161.98:4433/favicon.ico", verify=False, allow_redirects=False)
```

## System Information

    $ python -m requests.help

```json
zhizhuo@macbook ~ %  python3 -m requests.help
{
  "chardet": {
    "version": "5.0.0"
  },
  "charset_normalizer": {
    "version": "2.0.12"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.17"
  },
  "platform": {
    "release": "23.4.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.32.3"
  },
  "system_ssl": {
    "version": "30100020"
  },
  "urllib3": {
    "version": "1.26.6"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}
```
```json
└─#  python3 -m requests.help
/usr/lib/python3/dist-packages/requests/help.py:24: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib import pyopenssl
{
  "chardet": {
    "version": "5.1.0"
  },
  "charset_normalizer": {
    "version": "3.0.1"
  },
  "cryptography": {
    "version": "38.0.4"
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.2"
  },
  "platform": {
    "release": "6.1.0-kali7-arm64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30000080",
    "version": "23.0.0"
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "30000080"
  },
  "urllib3": {
    "version": "1.26.12"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": true
}
 
```
```json
zhizhuo@zhizhuo:~$ python3 -m requests.help
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": "3.4.8"
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.12"
  },
  "platform": {
    "release": "5.15.0-97-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30000020",
    "version": "21.0.0"
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "30000020"
  },
  "urllib3": {
    "version": "1.26.5"
  },
  "using_pyopenssl": true
}
```

**Comment by sigmavirus24** [comment] 2024-05-31 11:13
Duplicate of #6728

**Comment by sigmavirus24** [comment] 2024-05-31 11:16
Please copy and paste text, do not use screenshots as they are:

* Not searchable
* Not accessible to those who need to rely on screen readers or have issues with their vision

---

As to your actual error, just because you disable TLS Verification, does not mean that the rest of how TLS works is disabled. The client and server still need to agree upon cipher suites, TLS versions, etc. The server does not appear to support a TLS version that we also support.

You can verify this with `openssl s_client` which is well documented and has many examples online.

**Closed by sigmavirus24** 2024-05-31 11:16 UTC
