### ISSUE TITLE
Requests honor env no_proxy but will not respect no_proxy when passed as proxies dictionary

### ISSUE THREAD

**Issue by chriskvik** [psf/requests#6524] opened 2023-09-11 08:59 UTC
When working in a environment that uses proxies, most servers and clients will have proxy information set in their environment:

```
HTTP_PROXY=http://some-proxy.com:1234
HTTPS_PROXY=http://some-proxy.com:1234
NO_PROXY=example.com
```
Requests will respect these environment variables by default, meaning the following will work just fine.

```python
import requests

requests.get("https://example.com")
```

The snippet above will not use proxy, as specified with the `NO_PROXY` variable.

In requests we can also pass a proxy dict to requests, like this:

``` python
proxies = {
    "http": "http://some-proxy.com:1234",
    "https": "http://some-proxy.com:1234",
    "no": "example.com"  # Don't use the proxy for requests to example.com
}

requests.get("https://example.com", proxies=proxies)
```

But this wont work, request does not honor the `no` directive when passing proxies directly.

## Expected Result

I expect requests to bypass proxy when issuing a get towards example.com

## Actual Result

Requests tries to contact the proxy

## Reproduction Steps

See example above

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.2.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.3"
  },
  "platform": {
    "release": "6.2.0-31-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "30000020"
  },
  "urllib3": {
    "version": "2.0.4"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}

```

**Comment by sigmavirus24** [comment] 2023-09-12 12:43
Duplicate of #5000

**Closed by sigmavirus24** 2023-09-12 12:43 UTC
