### ISSUE TITLE
idna-3 is not supported

### ISSUE THREAD

**Issue by mgorny** [psf/requests#5804] opened 2021-04-28 22:58 UTC
idna-3 has been released on Jan 1st. However, requests still requires idna<3 preventing a lot of projects from upgrading.

## Expected Result

requests supporting idna-3.1

## Actual Result

requests force idna<3

## Reproduction Steps

Errr, install requests? ;-)

## System Information

```
$ python -m requests.help
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": "3.4.7"
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.4"
  },
  "platform": {
    "release": "5.11.16-gentoo-dist",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "101010bf",
    "version": "20.0.1"
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.26.4"
  },
  "using_pyopenssl": true
}
```

**Comment by nateprewitt** [comment] 2021-04-28 23:01
Hi @mgorny, this is a duplicate of #5710. Please be sure to check open issues before posting new ones. Thanks!

**Closed by nateprewitt** 2021-04-28 23:01 UTC
