### ISSUE TITLE
Wrong page in Pipy

### ISSUE THREAD

**Issue by carolcoral** [psf/requests#5528] opened 2020-07-10 06:44 UTC
# desc
URL:https://pypi.org/project/requests/
There have error in pipy page like this.
The CSS doesn`t get work.
![image](https://user-images.githubusercontent.com/8952687/87124674-c9e32180-c2bb-11ea-8316-8c0e9d92987f.png)

**Comment by sigmavirus24** [comment] 2020-07-10 13:09
Duplicate of #5501

**Closed** 2020-07-10 14:31 UTC
