### ISSUE TITLE
Redirection Code 308 (Permanent Redirect - POST to POST)

### ISSUE THREAD

**Issue by sartigas** [psf/requests#5587] opened 2020-09-15 21:58 UTC
Hi,

Not a request for help but a suggestion to the project team to review [RFC 7538](https://tools.ietf.org/html/rfc7538).

It would be awesome to have redirection code 308 (POST to POST) implemented in a future Requests release.

Thanks!

**Comment by sigmavirus24** [comment] 2020-09-15 23:32
@sartigas the issue is that as a client we can't know which servers reasonably support this as the majority of the web and a significant number of servers/applications pre-date this (relatively) recent RFC.

**Comment by nateprewitt** [comment] 2020-09-16 00:13
Hi @sartigas,

Just to clarify, are you asking about implementing redirect caching for a 308 response? Outside of that, 307 and 308 should operate to spec for redirects already.

**Comment by sigmavirus24** [comment] 2020-09-16 14:30
Also, we tried some naive caching and it introduced way too many side-effect issues

**Comment by sartigas** [comment] 2020-09-16 15:40
> Also, we tried some naive caching and it introduced way too many side-effect issues

Yeah, that's what I've seen by looking into some old threads. I stumbled upon the dreaded 301 POST -> GET redirection and didn't find a straight solution that's why I went a step further and found RFC 7538. I'll give this a try tweaking the source code in a test server.

Thanks! appreciate your inputs.

**Comment by nateprewitt** [comment] 2020-09-16 15:55
Yeah, caching has generally been problematic for Requests, so I think it's unlikely we'd implement any more.

> I stumbled upon the dreaded 301 POST -> GET redirection and didn't find a straight solution that's why I went a step further and found RFC 7538.

301, 302, and 303 will all downgrade POST -> GET and strip the headers/body from the request. We've explicitly marked 307 and 308 to ignore this functionality though, so you should be safe there if your server starts returning that status code.

It sounds like you've got a path forward, so I'll close this for now. Feel free to reopen this if you're finding the above isn't working as described.

**Closed by nateprewitt** 2020-09-16 15:55 UTC
