### ISSUE TITLE
Requests on pyth in 3 doesn't work the same as it does in python 2

### ISSUE THREAD

**Issue by jeffreydwalter** [psf/requests#5817] opened 2021-05-15 15:57 UTC
I'm having a problem with making an `OPTIONS` request. If I run the following code in `python 2.7` with `requests 2.7.0` it works fine and I get a `204` back. If I run it with `python 3.8.5` I get a `403`:
```
import requests
from requests_toolbelt.utils import dump

def print_raw_http(response):
    data = dump.dump_all(response, request_prefix=b'', response_prefix=b'')
    print('\n' * 2 + data.decode('utf-8'))

headers = {
    'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)',
}
session = requests.Session()
r = session.options('https://ocapi-app.arlo.com/api/auth', headers=headers)
print_raw_http(r)
r.raise_for_status()
```

```
$ python -V
Python 2.7.16

$ python3 -V
Python 3.8.5

$ pip freeze | grep requests
requests==2.7.0

$ pip3 freeze | grep requests
requests==2.7.0
```

`python 2.7`:
```
$ python blah.py 


OPTIONS /api/auth HTTP/1.1
Host: ocapi-app.arlo.com
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)
Content-Length: 0


HTTP/1.1 204 No Content
```

`python 3.8.5`:
```
$ python3 blah.py 


OPTIONS /api/auth HTTP/1.1
Host: ocapi-app.arlo.com
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 0


HTTP/1.1 403 Forbidden
```

Works fine with cURL too:
```
curl -vvvv -X OPTIONS "https://ocapi-app.arlo.com/api/auth" --output --http1.1 --no-alpn --no-npn -H "Host: ocapi-app.arlo.com" -H "Connection: keep-alive" -H "Accept-Encoding: gzip, deflate" -H "Accept: */*" -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)" -H "Content-length: 0"
```
```
> OPTIONS /api/auth HTTP/1.1
> Host: ocapi-app.arlo.com
> Connection: keep-alive
> Accept-Encoding: gzip, deflate
> Accept: */*
> User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)
> Content-length: 0
> 
< HTTP/1.1 204 No Content
```

**Comment by timthelion** [comment] 2021-05-17 16:03
When pasting code blocks it is much easier to read if you use three `` tics around the code block. See [these docs](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) for more information.

**Comment by jeffreydwalter** [comment] 2021-05-17 16:41
Yes, I know how to use markdown. That was a copy/paste fail while doing this from my phone.

See here if you want a formatted version: https://github.com/psf/requests/issues/5801#issuecomment-828925212

**Comment by sigmavirus24** [comment] 2021-05-19 00:25
Requests 2.7.0 is ancient and unsupported

**Comment by jeffreydwalter** [comment] 2021-05-19 19:20
@sigmavirus24 I'm a little confused about the versioning. According to pypi, requests is on [2.25.1](https://pypi.org/project/requests/)? What is the lastest stable version of requests?

**Comment by sethmlarson** [comment] 2021-05-19 20:50
@jeffreydwalter Your pip freeze in the original post indicates 2.7.0, not 2.25.1. Is this the case?

**Comment by jeffreydwalter** [comment] 2021-05-19 20:55
@sethmlarson, I was using 2.7.0, but I just installed requests==2.25.1, and the problem persists.

**Comment by jeffreydwalter** [comment] 2021-05-24 21:25
@sethmlarson @sigmavirus24  can you please reopen this issue. This issue is relevant and happens with 2.25.1 as well.

**Comment by jeffreydwalter** [comment] 2021-05-24 22:02
Thank you. Now that we're back in business, any thoughts about what the problem might be? The sample script I provided illustrates the problem.

**Comment by sigmavirus24** [comment] 2021-05-24 22:42
It seems like that requires auth. Can you reproduce this with some other website or just Arlo?

**Comment by jeffreydwalter** [comment] 2021-05-24 23:28
It's an OPTION request. If you run my test script in python 2.7 (or curl)
you'll see you get back a 2XX response and a 403 in python 3.x.

**Comment by nateprewitt** [comment] 2021-05-24 23:46
So, if you look at the response you're receiving @jeffreydwalter, you can see you're getting a CAPTCHA challenge from Cloudflare (not Arlo) because you've been identified as a bot.

I did a couple quick checks and the issue _appears_ to be related how Requests is interacting with Urllib3's cipher setting. Cloudflare is doing fingerprinting and anything using Requests on Python 3.8+ is getting auto blocked. I happened upon this finding by downgrading urllib3 to 1.24 which works. However, both 1.23 and 1.24.1 do not.

This is the [commit](https://github.com/urllib3/urllib3/pull/1463/) that was added back to 1.24.1 which fixed accidental removal of setting a default cipher in 1.24.0. I'd need to sit down for a minute to work out what we're passing into urllib3 for Python 3.8. This issue isn't reproducible using urllib3 alone, so it's specific to Requests.

There's also a question of whether we want to be in the business of trying to circumvent safety measures on services that have chosen to set them up. I'll do some more investigation if I find time but this sits pretty low on the priority list.

**Comment by nateprewitt** [comment] 2021-05-24 23:49
There's also a question of whether we want to be in the business of trying to circumvent safety measures on services that have chosen to set them up. I'll do some more investigation if I find time but this sits pretty low on the priority list.

**Comment by jeffreydwalter** [comment] 2021-05-24 23:59
That's fair. I appreciate you illuminating the issue. I assume Arlo put
that in place to block people from using python to automate management of
their personal cameras. There are 3-4 python libraries out there that
copied my library and all of them have been thwarted by this. I'd venture
there are a couple thousand users with broken home automation.

I'm happy to take a look at the code if you can point me in the right
direction. If not and you don't think this will get fixed in a reasonable
amount of time, I can rewrite my library to use httpx or something else.

Thanks again!

**Comment by jeffreydwalter** [comment] 2021-06-02 18:31
@nateprewitt I can confirm that downgrading my urllib3 to 1.24 makes the issue go away. I think this is worth digging into because I don't think it's just a case of CloudFlare blocking use of python or requests. There's probably a subtle protocol issue at play which is causing them to reject the requests.

**Comment by seanbreckenridge** [comment] 2021-06-03 03:40
```
httpx==0.18.1
  - certifi [required: Any, installed: 2021.5.30]
  - httpcore [required: >=0.13.0,<0.14.0, installed: 0.13.3]
    - h11 [required: >=0.11,<0.13, installed: 0.12.0]
    - sniffio [required: ==1.*, installed: 1.2.0]
  - rfc3986 [required: >=1.3,<2, installed: 1.5.0]
  - sniffio [required: Any, installed: 1.2.0]
requests==2.25.1
  - certifi [required: >=2017.4.17, installed: 2021.5.30]
  - chardet [required: >=3.0.2,<5, installed: 4.0.0]
  - idna [required: >=2.5,<3, installed: 2.10]
  - urllib3 [required: >=1.21.1,<1.27, installed: 1.24]
```

Created a pipenv with 1.24; ran the same script above, doesn't seem to fix my issue. So the issues we had were probably seaparate

```
$ pipenv run python3 main.py
{'count': 12, 'uniques': 12, 'clones': [{'timestamp': '2021-05-21T00:00:00Z', 'count': 7, 'uniques': 7}, {'timestamp': '2021-05-23T00:00:00Z', 'count': 1, 'uniques': 1}, {'timestamp': '2021-05-30T00:00:00Z', 'count': 1, 'uniques': 1}, {'timestamp': '2021-06-01T00:00:00Z', 'count': 1, 'uniques': 1}, {'timestamp': '2021-06-02T00:00:00Z', 'count': 2, 'uniques': 2}]}
succeeded
{'message': 'Must have push access to repository', 'documentation_url': 'https://docs.github.com/rest/reference/repos#get-repository-clones'}
failed
Traceback (most recent call last):
  File "/home/sean/Repos/requests_test/main.py", line 56, in <module>
    main()
  File "/home/sean/Repos/requests_test/main.py", line 52, in main
    make_request(requests.get, url, headers)
  File "/home/sean/Repos/requests_test/main.py", line 31, in make_request
    resp.raise_for_status()
  File "/home/sean/.local/share/virtualenvs/requests_test-YPmFob8P-python/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/seanbreckenridge/albums/traffic/clones
```

**Comment by sethmlarson** [comment] 2021-11-28 03:35
Yeah this isn't something that Requests can do much about, you're being detected as "requiring additional auth" but the goalposts for what individual services like Cloudflare will decide can change any day so closing this as not actionable by our team. Thanks for the report!

**Closed by sethmlarson** 2021-11-28 03:35 UTC

**Comment by jeffreydwalter** [comment] 2021-11-28 06:30
@sethmlarson what are you saying? You guys made a change to `urllib3` and/or `requests` that caused this issue. Downgrading to `urllib3` to `1.24` fixes the issue. The thing you can do about it is, fix the regression...
