### ISSUE TITLE
Add support for HTTP/2

### ISSUE THREAD

**Issue by Apteryks** [psf/requests#5757] opened 2021-02-18 12:52 UTC
It is my understanding that HTTP/2 is not currently supported by requests; hence this is a feature request (no pun intended) to add such support.

**Comment by sigmavirus24** [comment] 2021-02-20 15:04
Duplicate of #4604 and #5506

Requests is in a feature-freeze and is unlikely to add HTTP/2 in the future

**Closed by sigmavirus24** 2021-02-20 15:04 UTC
