### ISSUE TITLE
PyPi website description is showing HTML

### ISSUE THREAD

**Issue by LyalinDotCom** [psf/requests#5539] opened 2020-07-24 04:22 UTC
When viewing the package on PyPi using Edge I am seeing HTML where it should just be a text description.

**Details:**

* Browser: Edge (Chromium) version 84.0.522.40 (Official build) (64-bit)
* OS: Windows 10

## Screenshot of the problem:

![image](https://user-images.githubusercontent.com/2363526/88360396-5cf37100-cd2a-11ea-9d09-404f25d4896a.png)

**Comment by nateprewitt** [comment] 2020-07-24 04:25
Hi @LyalinDotCom, this is a dupe of #5501. Please make sure to check existing issues before posting new ones. Thanks!

**Closed by nateprewitt** 2020-07-24 04:25 UTC

**Comment by LyalinDotCom** [comment] 2020-07-24 04:52
Will do next time sorry 🙏

**Comment by ZenaMel** [comment] 2020-08-04 19:03
Why is this closed? The problem is still prevalent on both Firefox and Chrome.

![image](https://user-images.githubusercontent.com/47085752/89333803-cb72f000-d695-11ea-8b88-1c42b82ecb09.png)
(August 4, 2020)
