### ISSUE TITLE
"Authorization" header is rewritten for HTTP Basic Auth, even when it is explicitly set in the headers kwarg

### ISSUE THREAD

**Issue by terminalmage** [psf/requests#5419] opened 2020-04-11 21:28 UTC
I tried setting the `Authorization` header manually to make a request to the Github API, but authentication failed despite the same token working fine when making the request using cURL, `urllib.request.Request()`, and other methods. 

## Expected Result

Successful auth and a `200 OK` response.

## Actual Result

Authentication fails with a `401 Bad Credentials` response.

Upon inspecting the response's `request` attribute, I found that the `Authorization` header had been overwritten (looks like this happens [here](https://github.com/psf/requests/blob/9cdf294/requests/auth.py#L95-L97)).

I've since worked around this, but in my opinion, one should expect that if they are setting the `Authorization` header manually (rather than using the `auth` param), the header should not be overwritten.

I can draft a PR to address this if the project maintainers agree to such a change.

## Reproduction Steps

Create an [access token](https://github.com/settings/tokens) and then try to auth to the API like so:

```python
requests.get(
    'https://api.github.com/notifications',
    headers={'Authorization': 'token MY_TOKEN_HERE'}
)
```

## System Information

```python
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.2"
  },
  "platform": {
    "release": "5.6.3-arch1-1",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "1010106f"
  },
  "urllib3": {
    "version": "1.25.8"
  },
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment] 2020-04-12 15:19
> Upon inspecting the response's `request` attribute, I found that the `Authorization` header had been overwritten (looks like this happens [here](https://github.com/psf/requests/blob/9cdf294/requests/auth.py#L95-L97)).

I believe your diagnosis is wrong. You likely have a `.netrc` file with basic credentials in it and need to set `trust_env=False`.

**Comment by terminalmage** [comment] 2020-04-12 15:45
You're right. I knew about the .netrc parsing feature, but I just got a new laptop and imported my dotfiles using [chezmoi](https://github.com/twpayne/chezmoi) and didn't realize I had added an old .netrc file to chezmoi. After deleting it, auth works fine.

**Comment by sigmavirus24** [comment] 2020-04-12 15:47
This then becomes a duplicate of an issue about `trust_env`

**Closed** 2020-04-12 15:49 UTC
