### ISSUE TITLE
Documentation for trust_env not accessible.

### ISSUE THREAD

**Issue by chrzhang** [psf/requests#5264] opened 2019-11-15 03:01 UTC
[The link for trust_env documentation](https://2.python-requests.org//en/latest/api/#requests.Session.trust_env) fails to load.

**Comment by nicktimko** [comment] 2019-11-15 15:53
Duplicate of #5214

[Here's a working link](https://requests.kennethreitz.org/en/latest/api/#requests.Session.trust_env)

**Comment by xmo-odoo** [comment] 2019-11-21 07:12
The proper / canonical link should be https://requests.readthedocs.io/en/master/api/#requests.Session.trust_env however both indexation and intra-doc linking is currently a mess.

**Closed** 2019-12-11 04:19 UTC
