### ISSUE TITLE
Request: Limit SSL monkey patching for SNI support

### ISSUE THREAD

**Issue by JustinMaxwell** [psf/requests#5365] opened 2020-02-24 17:39 UTC
I'm requesting we reconsider the unconditional use of "urllib3.contrib.pyopenssl.inject_into_urllib3()".

Added 7 years ago, the goal was to "add SNI support for Python 2" #749 

"urllib3.contrib.pyopenssl.inject_into_urllib3()" is described to "Monkey-patch urllib3 with PyOpenSSL-backed SSL-support.": (https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/pyopenssl.py)

Request justification:
1: Security/stability: Monkey patching to swap out standard library use for a 3rd party library should arguably be more surgical, especially for ssl. If the patch is for support in Python2, then at least check for a major version. Or even better, check if SNI support is already present ssl.HAS_SNI.

2: Unnecessary: As of Dec. 10, 2014, the entirety of Python 3.4's ssl module has been backported for Python 2.7.9. See PEP 466 for justification. https://www.python.org/downloads/release/python-279/. This enables SNI support in the standard library for > v2.7.9

3: Inflexible: As implemented, there is no way to disable this behavior. The only option to prevent requests use of pyopenssl context is to uninstall pyopenssl for my entire python environment.
Summary.

@WhyNotHugo

**Comment by nateprewitt** [comment] 2020-04-30 16:14
Resolving as duplicate of #5267. We have a PR up now with the goal of only loading this as necessary going forward.

**Closed by nateprewitt** 2020-04-30 16:14 UTC

**Comment by JustinMaxwell** [comment] 2020-05-29 17:18
Don't use pyOpenSSL unless no SNI is detected #5443
